version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hemar
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  minio:
    image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    environment:
      MINIO_ROOT_USER: hemar
      MINIO_ROOT_PASSWORD: supersecretkey
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
  server:
    build: ./server
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/hemar?schema=public
      JWT_SECRET: supersecretjwt
      JWT_EXPIRES_IN: 1d
      CORS_ORIGINS: http://localhost:3000
      MONGO_URL: mongodb://mongo:27017/hemar
      ADMIN_EMAIL: admin@hemar.test
      ADMIN_PASSWORD: SuperSecure123!
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_ACCESS_KEY: hemar
      MINIO_SECRET_KEY: supersecretkey
      MINIO_BUCKET: hemar-assets
      MINIO_REGION: us-east-1
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - mongo
      - minio
    command: sh -c "npx prisma migrate deploy && npm run seed && npm run start"
  client:
    build: ./client
    environment:
      VITE_API_URL: http://localhost:4000/api
    ports:
      - '3000:3000'
    depends_on:
      - server
volumes:
  postgres-data:
  mongo-data:
  minio-data:
